# Generated by Django 2.2.5 on 2019-09-18 12:40

import cpffield.cpffield
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_nascimento', models.DateTimeField(blank=True, null=True)),
                ('cpf', cpffield.cpffield.CPFField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='RG')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('curso', models.CharField(blank=True, max_length=100, null=True)),
                ('bolsista', models.BooleanField(blank=True, default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('nome_professor', models.CharField(max_length=100)),
                ('carga_horaria', models.FloatField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', cpffield.cpffield.CPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('ra', models.CharField(max_length=9, unique=True, verbose_name='RA')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matriculas.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='materias',
            field=models.ManyToManyField(to='matriculas.Materia'),
        ),
    ]
