# Generated by Django 2.2.5 on 2019-09-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RG'),
        ),
    ]
