# Generated by Django 2.2.5 on 2019-09-11 13:01

from django.db import migrations, models
import matriculas.util.validatorsUtil


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[matriculas.util.validatorsUtil.validate_CPF]),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='ra',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
