# Generated by Django 2.2.5 on 2019-09-11 13:07

import cpffield.cpffield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_auto_20190911_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='cpf',
            field=cpffield.cpffield.CPFField(max_length=14, verbose_name='CPF'),
        ),
    ]
