# Generated by Django 2.2.5 on 2019-09-11 13:23

import cpffield.cpffield
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0003_auto_20190911_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('nome_professor', models.CharField(max_length=100)),
                ('carga_horaria', models.FloatField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='matricula',
            name='cpf',
            field=cpffield.cpffield.CPFField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('materias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.Materia')),
            ],
        ),
    ]
