# Generated by Django 2.2.5 on 2019-09-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0005_auto_20190911_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='materias',
        ),
        migrations.AddField(
            model_name='curso',
            name='materias',
            field=models.ManyToManyField(to='matriculas.Materia'),
        ),
    ]
