# Generated by Django 2.2.5 on 2019-09-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0006_auto_20190911_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
