# Generated by Django 2.2.5 on 2019-09-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0007_matricula_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='observacoes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='ra',
            field=models.CharField(max_length=8, unique=True, verbose_name='RA'),
        ),
    ]
