# Generated by Django 2.2.5 on 2019-09-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0007_aluno_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(default='matriculas\\static\\images\\pipiu.jpg', upload_to='pic_folder/'),
        ),
    ]
