# Generated by Django 2.2.5 on 2019-09-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0008_auto_20190918_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(default='static/images/pipiu.jpg', upload_to='static/images/'),
        ),
    ]
