# Generated by Django 2.2.4 on 2019-09-13 00:27

import cpffield.cpffield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0008_auto_20190911_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='cpf',
            field=cpffield.cpffield.CPFField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
