# Generated by Django 2.2.5 on 2019-09-17 14:43

import cpffield.cpffield
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0009_auto_20190912_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='cpf',
            field=cpffield.cpffield.CPFField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matriculas.Curso'),
        ),
    ]
