# Generated by Django 2.2.5 on 2019-09-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0010_auto_20190917_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='ra',
            field=models.CharField(max_length=9, unique=True, verbose_name='RA'),
        ),
    ]
