# Generated by Django 2.2.5 on 2019-09-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0011_auto_20190919_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='foto',
        ),
    ]
