# Generated by Django 2.2.5 on 2019-09-17 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0011_auto_20190917_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dt_nascimento', models.DateTimeField()),
                ('rg', models.CharField(max_length=9, unique=True, verbose_name='RG')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('bolsista', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cpf', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matriculas.Matricula')),
                ('curso', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matriculas.Curso')),
            ],
        ),
    ]
