# Generated by Django 2.2.5 on 2019-09-17 19:23

import cpffield.cpffield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0012_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=cpffield.cpffield.CPFField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(max_length=100),
        ),
    ]
